import "serialize.zc";

fn test_string_view() {
    let sv1 = StringView::from("1020");
    println "{sv1}"
    let sv2 = StringView::from_parts("1020", 4);
    assert(sv1 == sv2);

    let sv3: StringView = sv1.chop_by_delim('0');
    println "{sv3}\n{sv1}\n"

    let sv4 = StringView::from(
"""struct StringViewLineIter {{
    sv: StringView;
}}

impl StringViewLineIter {{
    fn next(self) -> Option<StringView> {{
        if(self.sv.len == 0) return Option<StringView>::None();

        let line = self.sv.chop_by_line();
        return Option<StringView>::Some(line);
    }}
}}
""");

    let lineIdx = 0;
    for l in sv4.get_line_iterator() {
        printf("%lu:\t", lineIdx);
        l.println();
        lineIdx++;
    }
}

fn main() {
    "hello world";
    test_string_view();
}