import "string_view.zc"
import "std/string.zc"

def SerializeType_JSON = 0;
def SerializeType_C99_Initializer = 1;
def SerializeType_XML = 2;
def SerializeType_TOML = 3;

def SerializeScope_Object = 0;
def SerializeScope_Array = 1;

struct SerializeScope {
    type: u8;
    prevNeedsComma: bool;
    didKey: bool;
    scopeNeedsNewline: bool; // for TOML
    currentElem: StringView;
    arrayElemName: StringView;
    arrayElemIdx: u32;
}

struct SerializationContext_ {
    scopes: Vec<SerializeScope>;
    currentElem: StringView;
    floatFmt: char*;
    indent: u8;
    shouldQuoteStrings: bool;

    // for TOML:
    ignoreElementBegin: bool;
    doneFirstObject: bool;
    shouldPushScope: bool;
    scopeTypeToPush: u8;
    countNonNewlineScopes: usize;

    // for XML:
    shouldPopScope: bool;
}

// TODO: Port deserialization
struct DeserializationContext_ {
    ignore: u8;
}

union SerializeDeserializeUnion {
    serialize: SerializationContext_;
    deserialize: DeserializationContext_;
}

struct SerializeContext {
    type: u8;
    isSerializing: bool;
    output: String,

    as: SerializeDeserializeUnion;

    ObjectBegin_Impl: fn*(SerializeContext*) -> bool;
    AttributeName_Impl: fn*(SerializeContext*, StringView) -> bool;
    ObjectEnd_Impl: fn*(SerializeContext*) -> bool;
    ArrayBegin_Impl: fn*(SerializeContext*, StringView) -> bool;
    ArrayEnd_Impl: fn*(SerializeContext*) -> bool;

    SerializeNull_Impl: fn*(SerializeContext*) -> bool;
    SerializeOpBool_Impl: fn*(SerializeContext*, bool*) -> bool;
    SerializeOpInt_Impl: fn*(SerializeContext*, i64*) -> bool;
    SerializeOpFloat_Impl: fn*(SerializeContext*, f64*) -> bool;
    SerializeOpString_Impl: fn*(SerializeContext*, char**) -> bool;
    SerializeOpView_Impl: fn*(SerializeContext*, StringView*) -> bool;

    // Internals
    ElementBegin: fn*(SerializeContext*);
    ElementEnd: fn*(SerializeContext*);
}

impl SerializeContext {
    fn serialize(type: u8, indent: u8 = 0, floatFmt: char* = "%lf") -> SerializeContext {
        let result: SerializeContext;
        result.type = type;
        result.isSerializing = true;
        result.as.serialize.indent = indent;
        result.as.serialize.floatFmt = floatFmt;

        if type == SerializeType_JSON {
            // TODO
        } else {
            // the rest come after, I'm doing json first
            assert(false);
        }
    }
}

