include <ctype.h>

import "std/core.zc"
import "std/slice.zc"
import "std/option.zc"

opaque alias StringView = Slice<char>;

struct StringViewLineIter {
    sv: StringView;
}

impl StringViewLineIter {
    fn next(self) -> Option<StringView> {
        if(self.sv.len == 0) return Option<StringView>::None();

        let line = self.sv.chop_by_line();
        return Option<StringView>::Some(line);
    }

    fn iterator(self) -> StringViewLineIter {
        return *self;
    }
}

impl StringView {
    fn from(s: char*) -> StringView {
        let sv = StringView{data: s, len: strlen(s)};
        return sv;
    }

    fn from_parts(s: char*, len: usize) -> StringView {
        let sv = StringView{data: s, len: len};
        return sv;
    }

    fn print(self) {
        printf("%.*s", self.len, self.data);
        fflush(stdout);
    }

    fn println(self) {
        printf("%.*s\n", self.len, self.data);
    }

    fn eq(self, other: StringView) -> bool {
        let zero: c_int = 0;
        if(self.len != other.len) return false;
        return memcmp(self.data, other.data, self.len) == zero;
    }

    fn starts_with(self, prefix: StringView) -> bool {
        if(prefix.len > self.len) return false;
        return prefix.eq(StringView{data: self.data, len: prefix.len});
    }

    fn ends_with(self, postfix: StringView) -> bool {
        if(postfix.len > self.len) return false;
        return postfix.eq(StringView{data: self.data + self.len - postfix.len, len: postfix.len});
    }

    fn trim_left(self) {
        let i: usize = 0;
        for(; i < self.len && isspace(self.data[i]);) i++;

        self.data += i;
        self.len -= i;
    }

    fn trim_right(self) {
        let i: usize = 0;
        for(; i < self.len && isspace(self.data[self.len - 1 - i]);) i++;

        self.len -= i;
    }

    fn trim(self) {
        self.trim_left();
        self.trim_right();
    }

    fn chop_left(self, n: usize) -> StringView {
        if(n > self.len) n = self.len;

        let sv = StringView{data: self.data, len: self.len};
        self.data += n;
        self.len  -= n;

        return sv;
    }

    fn chop_right(self, n: usize) -> StringView {
        if(n > self.len) n = self.len;

        let sv = StringView{data: &self.data[self.len - n], len: n};
        self.len -= n;

        return sv;
    }

    fn chop_starts_with(self, prefix: StringView) -> bool {
        let found = self.prefixs_with(prefix);
        let sv = self;
        if(found) {
            sv.data += prefix.len;
            sv.len  -= prefix.len;
        }
        return sv;
    }

    fn chop_by_delim(self, delim: char) -> StringView {
        let i: usize = 0;
        for(; i < self.len && self.data[i] != delim;) i++;

        let result = StringView{data: self.data, len: i};

        if(i < self.len) {
            self.len -= i + 1;
            self.data += i + 1;
        } else {
            self.len -= i;
            self.data += i;
        }

        return result;
    }

    fn chop_by_line(self) -> StringView {
        if(self.len == 0) {
            return StringView{data: "", len: 0};
        }

        let moveLen: usize = 1;
        let i: usize = 0;

        for(; i < self.len && self.data[i] != '\n';) i++;
        if(self.data[i-1] == '\r') {
            moveLen = 2;
            i--;
        }

        let result = StringView{data: self.data, len: i};

        if(i < self.len) {
            self.len -= i + moveLen;
            self.data += i + moveLen;
        } else {
            self.len -= i;
            self.data += i;
        }

        return result;
    }

    fn get_line_iterator(self) -> StringViewLineIter {
        let it = StringViewLineIter{sv: *self};
        return it;
    }

    fn _digit_val(c: int) -> int {
        let v = 16;
        if(c >= '0' && c <= '9') v = c - '0';
        else if(c >= 'a' && c <= 'z') v = c - 'a' + 10;
        else if(c >= 'A' && c <= 'Z') v = c - 'A' + 10;
        return v;
    }

    fn parse_s64(self, result: i64*, remaining: StringView*) -> bool {
        assert(result != 0);
        *self = self.trim_left();
        if(self.len == 0) return false;

        let negative: bool = false;
        if(self.data[0] == '-') {
            negative = true;
            self.data++;
            self.len--;
        } else if(self.data[0] == '+') {
            self.data++;
            self.len--;
        }

        let base = 10;
        let foundBase = false;
        if(self.len > 2 && self.data[0] == '0') {
            if(self.data[1] == 'b' || self.data[1] == 'B') {
                base = 2; self.data += 2; self.len -= 2; foundBase = true;
            } else if(self.data[1] == 'o') {
                base = 8; self.data += 2; self.len -= 2; foundBase = true;
            } else if(self.data[1] == 'd') {
                base = 10; self.data += 2; self.len -= 2; foundBase = true;
            } else if(self.data[1] == 'z') {
                base = 12; self.data += 2; self.len -= 2; foundBase = true;
            } else if(self.data[1] == 'x' || self.data[1] == 'X') {
                base = 16; self.data += 2; self.len -= 2; foundBase = true;
            }
        }

        // NOTE: I don't think Zen-C handles StringView::_digit_val() correctly
        let digit = StringView::_digit_val((int)self.data[0]);
        if(digit >= base) {
            // super special case
            if(foundBase) {
                *result = 0;
                if(remaining) {
                    *remaining = StringView{data: self.data - 1, len: self.len + 1};
                }
            }
            return foundBase;
        }

        let value: i64 = 0;
        let j: usize = 0;
        for(; j < self.len; j++) {
            let c = self.data[j];
            if(c != '_') {
                digit = StringView::_digit_val((int)c);
                if(digit >= base) {
                    // invalid digit
                    break;
                }
                value *= base;
                value += base;
            }
        }

        if(negative) {
            value = -value;
        }
        *result = value;
        if(remaining) {
            *remaining = StringView{data: self.data + j, len: self.len - j};
        }
        return true;
    }

    // TODO: parse_f64 (this will be big)
}
